import Head from "next/head";
import FormManager from "../components/FormManager";
import Instruction from "../components/Instruction";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Instruction />
      </main>

      <footer></footer>
    </div>
  );
}
